---
title: "R Notebook"
output: html_notebook
---
```{r}
#Function -> price.ani_ag
#not given same name as using animation package also to get the data 
price.ani_ag = function(
  price, time, time.begin = min(time), span = 15 * 60, ..., xlab = 'price',
  ylab = 'frequency', xlim, ylim, main
) {
  time1 = time.begin
  miss.main = missing(main)
  tab.max = 0
  
  #{snipet1:}
  while (time1 < max(time)) {
    time2 = time1 + span
    sub.price = price[time >= time1 & time <= time2]
    if (length(sub.price) > 0) {
      tab.max = max(tab.max, max(table(sub.price)))
    }
    time1 = time2
  }

  if (missing(xlim))
    xlimit = range(price)
  if (missing(ylim))
    ylimit = c(0, tab.max)
  
  #{snipet2: creating dataframe}
  time1 = time.begin
  i <- 1
  full_dat <- data.frame()
  time_data <- data.frame()
  while (time1<max(time)) {
    time2 = time1 + span
    sub.price<-price[time>=time1 & time<=time2]
    if (length(sub.price)>0) {
      tab.price <- table(sub.price)
      count = length(tab.price)
      sub.iteration <- vector(length = count, mode = "numeric")
      sub.iteration <- sub.iteration + 1
      temp_df<-data.frame(tab.price, iteration=sub.iteration*i)
      full_dat<-rbind(full_dat, temp_df)
      if(miss.main) {
        main = paste(time1, time2, sep = ' - ')
        temp_df_name <- data.frame(main, iteration = i)
        time_data <- rbind(time_data, temp_df_name)
      }
      i <- i + 1
    }
    
    time1 = time2
  }
  invisible(list(full_data = full_dat, dur_data = time_data, xl = xlimit, yl = ylimit))
}
```

```{r}
#Getting data using animation
library(animation)
df <- vanke1127
full_data <- price.ani_ag(df$price, df$time)$full_data
#convert sub.price to numeric for axis
full_data$sub.price = as.numeric(levels(full_data$sub.price))[full_data$sub.price]
time_data <- price.ani_ag(df$price, df$time)$dur_data
xlimit <- price.ani_ag(df$price, df$time)$xl
ylimit <- price.ani_ag(df$price, df$time)$yl
```

```{r}
#plotting using animint
library(animint)

mid_x = (xlimit[1] + xlimit[2])/2

theme_config = theme(plot.background = element_rect(fill = "lightsteelblue", colour = "red"), plot.title = element_text(size = 20, face="bold", hjust = 0.5), 
        plot.caption = element_text(size = 10), 
        axis.text.x = element_text(size = 5, angle=30, hjust = 0.5), 
        axis.text.y = element_text(size=10, angle = 30), 
        panel.background = element_rect(fill = "lightsteelblue2"),
        panel.grid.major = element_line(linetype = "dashed"),
        panel.grid.minor = element_blank())  

gg <- ggplot(full_data)  + geom_point(data=full_data,  aes(x = sub.price, y=Freq, showSelected=iteration)) + 
  geom_segment(data=full_data, aes(x = sub.price, xend = sub.price, y = Freq, yend = 0, showSelected=iteration)) + 
  geom_text(data=time_data, aes(x = mid_x, y = ylimit[2] + 2, label = main, showSelected = iteration)) + coord_cartesian(xlim = xlimit, ylim = c(ylimit[1], ylimit[2] + 2)) + scale_x_continuous(breaks=seq(xlimit[1], xlimit[2], 0.1)) + scale_y_continuous(breaks=seq(ylimit[1], ylimit[2] + 2, 5)) + theme_config + ggtitle("Frequency of Prices") + xlab("price") + ylab("Frequency")


viz <- list(plot = gg, 
            time = list(variable = "iteration", ms = 1000), 
            title = "frequency of stock prices")
animint2dir(viz, out.dir = "price.ani")
animint2gist(viz, out.dir = "grad.desc")
```



